twitter:
  consumerKey: <Twitter app consumer key>
  consumerSecret: <Twitter app consumer secret>
  accessToken: <Twitter account access token>
  accessTokenSecret: <Twitter account access token secret>
  user: <Twitter handle>
telegram:
  chatId: <Telegram cha id>
  token: <Telegram bot token>
